# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.cache/wt [current_project]
set_property parent.project_path C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/Mux_JalToWn.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/Mux_JalToWdata.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/Mux_WData.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/SignExtend.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/regfile.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/program_counter.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/Mux_regfile.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/Mux_Alub.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/Mux_Alua.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/Mux4to1.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/control.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/branch_adder.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/adder.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/ALU.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/data_mem.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/inst_mem.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/CPU.v
  C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/sources_1/new/sccomp.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/constrs_1/imports/Desktop/ZYBO_MASTER.xdc
set_property used_in_implementation false [get_files C:/Users/Ryan/Desktop/CMPEN_final_project/final_project/final_project.srcs/constrs_1/imports/Desktop/ZYBO_MASTER.xdc]


synth_design -top sccomp -part xc7z010clg400-1


write_checkpoint -force -noxdef sccomp.dcp

catch { report_utilization -file sccomp_utilization_synth.rpt -pb sccomp_utilization_synth.pb }
